#!/bin/sh
APPDIR="$( cd "$( dirname "$0" )" && pwd )"
JAVA=java
$JAVA -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib:$APPDIR/lib/jycessing" -ea -cp "$APPDIR/lib/jycessing/core.jar:$APPDIR/lib/jycessing/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/jycessing/gluegen-rt.jar:$APPDIR/lib/jycessing/guava-17.0.jar:$APPDIR/lib/jycessing/jogl-all-natives-linux-i586.jar:$APPDIR/lib/jycessing/jogl-all.jar:$APPDIR/lib/jycessing/jython.jar:$APPDIR/lib/jycessing/PythonMode.jar" -splash:"$APPDIR/lib/jycessing/splash.png" jycessing.Runner --noredirect --exported fullScreen BGCOLOR=#666666 --stop-color=#cccccc "$APPDIR/source/liveEdu.pyde"
